auto: true
title: Sharing Agreement
permalink: /:categories/:title/
exclude: README.md

keywords: ['sharism', '&#20998;&#20139;&#20027;&#20041;', 'isaac mao', 'isaacmao', 'beijing', 'china', 'culture', 'creativecommons', 'freeculture', 'sharing', 'slowfi', 'rejon', 'christopheradams']
